[CI] Add a check in merge workflow to not allow master.

diff --git a/.github/workflows/merge-major-version.yml b/.github/workflows/merge-major-version.yml
--- a/.github/workflows/merge-major-version.yml
+++ b/.github/workflows/merge-major-version.yml
@@ -21,6 +21,19 @@ jobs:
       merge-into-branch: ${{ steps.determine-merge-branch.outputs.branch }}
 
     steps:
+      - name: Ensure not using master
+        id: determine-merge-branch
+        env:
+          BRANCH: ${{ github.ref_name }}
+        run: |
+          if [ "$BRANCH" == "master" ]; then
+            echo "Cannot use master to merge up. Master is highest."
+
+            exit 1
+          else
+            echo "Not using master. Proceed."
+          fi
+
       - name: Generate a token
         id: generate-token
         uses: actions/create-github-app-token@v2
