[CI] Update Release Workflow (#122)
# Description

Update the release workflow with a few fixes and a new version checker.

- [X] Bug fix _(non-breaking change which fixes an issue)_
- [X] New feature _(non-breaking change which adds functionality)_

diff --git a/.github/workflows/release-new-version.yml b/.github/workflows/release-new-version.yml
--- a/.github/workflows/release-new-version.yml
+++ b/.github/workflows/release-new-version.yml
@@ -13,7 +13,29 @@ permissions:
   contents: write
 
 jobs:
+  check-version:
+    name: Validate Release Version
+
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Validate Format
+        env:
+          VERSION: ${{ inputs.version }}
+        run: |
+          # Update this when new major releases are made (25|26) for example.
+          # Format is (MINIMUM_MAJOR_VERSION_SUPPORTED|CURRENT_MAJOR_VERSION_SUPPORTED)
+          if [[ $VERSION =~ ^v(25).([0-9]+).([0-9]+)$ ]]; then
+            echo "Valid version"
+          else
+            echo "Invalid version passed"
+
+            exit 1
+          fi
+
   check-composer:
+    needs: check-version
+
     strategy:
       matrix:
         paths:
@@ -42,7 +64,7 @@ jobs:
 
     name: "Check ${{ matrix.paths.name }} Composer For Updates"
 
-    runs-on: 'ubuntu latest'
+    runs-on: ubuntu-latest
 
     steps:
       - name: Checkout repository
@@ -76,7 +98,7 @@ jobs:
 
     name: Release ${{ inputs.version }}
 
-    runs-on: ubuntu-24.04
+    runs-on: ubuntu-latest
 
     outputs:
       version: ${{ steps.version.outputs.version }}
